import Config

# Configure your database
config :trivia_advisor, TriviaAdvisor.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "trivia_advisor_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
# Binding to loopback ipv4 address prevents access from other machines.
config :trivia_advisor, TriviaAdvisorWeb.Endpoint,
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: 4000],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "WCzadwV1qqYwGc1+JsaMIQQhnGODBiXqM2DfyG+evmsNidNYhNnsHWAc4ElI5tdY",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:trivia_advisor, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:trivia_advisor, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :trivia_advisor, TriviaAdvisorWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/trivia_advisor_web/(controllers|live|components)/.*(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :trivia_advisor, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set logger level to warn to reduce noise in logs
config :logger, level: :warning

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Set environment tag
config :trivia_advisor, env: :dev

# Disable Ecto SQL query logging to reduce console spam
config :logger, Ecto.LogEntry, level: :warning

# Disable LiveView debug instrumentation
config :phoenix_live_view, debug: false

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Disable HEEx debug annotations to reduce log noise
  debug_heex_annotations: false,
  # Disable expensive runtime checks to improve performance
  enable_expensive_runtime_checks: false

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

# Add the Google Maps API key config
config :trivia_advisor, TriviaAdvisor.Scraping.GoogleAPI,
  google_maps_api_key: System.get_env("GOOGLE_MAPS_API_KEY")

# Explicitly set Oban plugins for dev (no Cron)
config :trivia_advisor, Oban,
  plugins: [
    # No Cron plugin in development
    {Oban.Plugins.Pruner, max_age: 604800}  # 7 days in seconds
  ]
